---
driver_plugin: vagrant

platforms:
- name: ubuntu-10.04_chef-10
  driver_config:
    box: sendgrid_ubuntu-10.04_chef-10
    box_url: http://repo.sendgrid.net/sendgrid_ubuntu-10.04_chef-10.box
- name: centos-6_chef-10
  driver_config:
    box: sendgrid_centos-6_chef-10
    box_url: http://repo.sendgrid.net/sendgrid_centos-6_chef-10.box
    network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["forwarded_port", {guest: 2003, host: 2003}]
      - ["forwarded_port", {guest: 2004, host: 2004}]
      - ["forwarded_port", {guest: 8126, host: 8126}]
- name: centos-6_chef-11
  driver_config:
    box: sendgrid_centos-6_chef-11
    box_url: http://repo.sendgrid.net/sendgrid_centos-6_chef-11.box
suites:
- name: default
  run_list: ["recipe[graphite]"]
  attributes: {}
